# Header
nav:
  Categories: /category
  #Tags: /tag
  About: /about

# favicon
favicon: /logo.svg

# logo
logo: /logo.svg

# links
links:
  # Github: https://github.com/xbmlz
  # ZhiHu:
  # Twitter:
  # Weibo:
  Bilibili: https://space.bilibili.com/10838981


# mathjax
fancybox: false

# mathjax
mathjax: false

# echarts
echarts: false

# busuanzi
busuanzi: false

# mermaid
mermaid:
  enable: false
 
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: infine-zero/giscus
  repo_id: R_kgDOJXiISw
  category: Announcements
  category_id: DIC_kwDOJXiIS84CV0ca
  mapping: url
  strict: "0"
  reactions-enabled: "1"
  theme: "preferred_color_scheme"
  data-lang: "zh-CN"
  crossorigin: "anonymous"

# RSS订阅
rss: /atom.xml
sidebar_rss:
  text: RSS
  icon: fa fa-rss
  color: burlywood
  link: atom.xml